-- Lấy thông tin loại sản phẩm của từng sản phẩm (select TenSanPham, TenLoai)
SELECT TENSP , TENLOAI FROM SANPHAM 
INNER JOIN LOAISANPHAM ON SANPHAM.LOAISPID = LOAISANPHAM.LOAISPID ;
-- In ra danh sách các sản phẩm không bán được trong năm 2019
SELECT * FROM SANPHAM 
JOIN LOAISANPHAM ON SANPHAM.LOAISPID = LOAISANPHAM.LOAISPID 
JOIN CHITIETDONDATHANG ON SANPHAM.SPID = CHITIETDONDATHANG.SPID
JOIN DONDATHANG ON CHITIETDONDATHANG.DONDHID = DONDATHANG.DONDHID
WHERE YEAR(DONDATHANG.NGAYDAT) != '2019' 
;
-- In ra danh sách sản phẩm thuộc loại "Đồ ăn" sản xuất và được bán ra trong ngày 25/5/2020 (sản xuất và bán ra là cùng 1 ngày)
SELECT * FROM SANPHAM 
JOIN LOAISANPHAM ON SANPHAM.LOAISPID = LOAISANPHAM.LOAISPID 
JOIN CHITIETDONDATHANG ON SANPHAM.SPID = CHITIETDONDATHANG.SPID
JOIN DONDATHANG ON CHITIETDONDATHANG.DONDHID = DONDATHANG.DONDHID
WHERE LOAISANPHAM.TENLOAI = 'ĐỒ ĂN' AND DONDATHANG.NGAYDAT = '2020-05-25' ;
-- Tìm các số hiệu đơn đã mua sản phẩm thuộc loại sản phẩm "Đồ ăn" hoặc "Đồ uống", mỗi sản phẩm mua với số lượng từ 10 đến 20.
SELECT * FROM SANPHAM 
JOIN LOAISANPHAM ON SANPHAM.LOAISPID = LOAISANPHAM.LOAISPID 
JOIN CHITIETDONDATHANG ON SANPHAM.SPID = CHITIETDONDATHANG.SPID
JOIN DONDATHANG ON CHITIETDONDATHANG.DONDHID = DONDATHANG.DONDHID
WHERE LOAISANPHAM.TENLOAI IN ( 'ĐỒ ĂN' , 'ĐỒ UỐNG' ) AND CHITIETDONDATHANG.SOLUONG BETWEEN 10 AND 20 ;
-- In ra tổng tiền của các hóa đơn trong ngày 25/05/2020
SELECT CHITIETDONDATHANG.DONDHID ,CHITIETDONDATHANG.SOLUONG , SANPHAM.GIABAN  , (SANPHAM.GIABAN * CHITIETDONDATHANG.SOLUONG ) TONGTIEN FROM CHITIETDONDATHANG 
JOIN SANPHAM ON SANPHAM.SPID = CHITIETDONDATHANG.SPID
JOIN DONDATHANG ON CHITIETDONDATHANG.DONDHID = DONDATHANG.DONDHID
WHERE DONDATHANG.NGAYDAT = '2020-05-25' 
-- GROUP BY CHITIETDHID
HAVING SANPHAM.SPID = SANPHAM.GIABAN * CHITIETDONDATHANG.SOLUONG 
;
-- Tính tổng số sản phẩm của từng hóa đơn
SELECT DISTINCT CHITIETDONDATHANG.DONDHID , SUM(CHITIETDONDATHANG.SOLUONG) TONGSANPHAM FROM SANPHAM 
JOIN CHITIETDONDATHANG ON SANPHAM.SPID = CHITIETDONDATHANG.SPID
-- JOIN DONDATHANG ON CHITIETDONDATHANG.DONDHID = DONDATHANG.DONDHID
GROUP BY CHITIETDONDATHANG.DONDHID ORDER BY CHITIETDONDATHANG.DONDHID ;
-- Tìm khách hàng có số lần mua hàng nhiều nhất.
SELECT DONDATHANG.KHID KHACHANG, COUNT(DONDATHANG.SOHIEUDON) TONGDH FROM KHACHHANG
JOIN DONDATHANG ON KHACHHANG.KHID = DONDATHANG.KHID
GROUP BY DONDATHANG.KHID
ORDER BY TONGDH DESC LIMIT 1 ;
-- Tìm hóa đơn có mua 3 sản phẩm do Việt Nam sản xuất (3 sản phẩm khác nhau)
SELECT DONDATHANG.DONDHID , COUNT(CHITIETDONDATHANG.SPID) SLL FROM SANPHAM 
JOIN CHITIETDONDATHANG ON SANPHAM.SPID = CHITIETDONDATHANG.SPID
JOIN DONDATHANG ON  CHITIETDONDATHANG.DONDHID = DONDATHANG.DONDHID
WHERE SANPHAM.NHASX = 'VIỆT NAM' 
GROUP BY DONDATHANG.DONDHID
HAVING SLL =  3 
;
-- Tháng mấy trong năm 2019 có doanh số bán hàng cao nhất ? note
SELECT month(DONDATHANG.NGAYDAT) thang , SUM(CHITIETDONDATHANG.SOLUONG * SANPHAM.GIABAN) giaban FROM SANPHAM 
JOIN CHITIETDONDATHANG ON SANPHAM.SPID = CHITIETDONDATHANG.SPID
JOIN DONDATHANG ON CHITIETDONDATHANG.DONDHID = DONDATHANG.DONDHID
WHERE YEAR(DONDATHANG.NGAYDAT) = '2019' 
group by thang
order by giaban desc LIMIT 1
;
-- Cho biết trị giá hóa đơn cao nhất là bao nhiêu ?
SELECT ddh.dondhid , SUM(CTDDH.soluong * SP.GIABAN) GIATONGDON FROM dondathang DDH 
JOIN chitietdondathang CTDDH ON CTDDH.dondhid = DDH.dondhid 
JOIN SANPHAM SP ON CTDDH.spid = SP.SPID
GROUP BY ddh.dondhid
order by GIATONGDON DESC LIMIT 1
;
-- Cho biết trị giá hóa đơn cao nhất và thấp nhất là bao nhiêu ?
WITH InvoiceValues AS
( SELECT ddh.dondhid , SUM(CTDDH.soluong * SP.GIABAN) GIATONGDON  FROM dondathang DDH 
JOIN chitietdondathang CTDDH ON CTDDH.dondhid = DDH.dondhid 
JOIN SANPHAM SP ON CTDDH.spid = SP.SPID
GROUP BY ddh.dondhid 
order by GIATONGDON DESC ) 
SELECT MAX(GIATONGDON) MAXGIA , MIN(GIATONGDON) MINGIA FROM InvoiceValues
;
-- Tìm sản phẩm có tổng số lượng bán ra thấp nhất trong năm 2019
SELECT SP.SPID , MIN(CTDDH.SOLUONG) MINSP FROM SANPHAM SP
JOIN chitietdondathang CTDDH ON CTDDH.spid = SP.SPID
JOIN dondathang DDH ON CTDDH.dondhid = DDH.dondhid
WHERE YEAR(DDH.ngaydat) = 2019  
GROUP BY SP.SPID
order by MINSP ASC LIMIT 1 ;
-- Loại sản phẩm nào bán chạy nhất từ đầu năm đến nay ? (số lượng bán ra của sản phẩm thuộc loại đó là nhiều nhất)
SELECT LSP.LOAISPID , CTDDH.SOLUONG SLDON FROM LOAISANPHAM LSP 
JOIN SANPHAM SP ON SP.loaisPID = LSP.LOAISPID
JOIN chitietdondathang CTDDH ON CTDDH.spid = SP.SPID
GROUP BY LSP.LOAISPID , CTDDH.SOLUONG 
order by SLDON DESC LIMIT 1
;
-- Tìm những loại sản phẩm được bán ra trong ngày 9/6/2020
SELECT *  FROM SANPHAM SP
JOIN chitietdondathang CTDDH ON CTDDH.spid = SP.SPID
JOIN dondathang DDH ON CTDDH.dondhid = DDH.dondhid
WHERE DDH.NGAYDAT = '2020-06/09' ;
-- Tìm những khách hàng ở Hà Nội đã mua sản phẩm thuộc loại 1 trong tháng 6 năm 2020
SELECT *  FROM KHACHHANG KH
JOIN dondathang DDH ON KH.khid = DDH.khid
JOIN chitietdondathang CTDDH ON CTDDH.dondhid = DDH.dondhid
JOIN SANPHAM SP ON SP.SPID = CTDDH.spid
JOIN LOAISANPHAM LSP ON SP.LOAISPID = LSP.LOAISPID
WHERE KH.DIACHI = 'HÀ NỘI' AND MONTH(DDH.ngaydat) = 6 AND YEAR(DDH.ngaydat) = 2020 AND LSP.LOAISPID = 1 ;
-- Tìm những sản phẩm chưa bán được trong 6 tháng vừa qua
SELECT SP.SPID FROM SANPHAM SP
JOIN chitietdondathang CTDDH ON CTDDH.spid = SP.spid
JOIN dondathang DDH ON DDH.dondhid = CTDDH.dondhid
WHERE SP.SPID != ( MONTH(DDH.NGAYDAT) = 6 )
GROUP BY SP.SPID ;
-- Tìm những hóa đơn có 3 loại sản phẩm khác nhau.
SELECT DDH.DONDHID FROM dondathang DDH
JOIN chitietdondathang CTDDH ON CTDDH.dondhid = DDH.dondhid 
JOIN SANPHAM SP ON SP.SPID = CTDDH.spid
GROUP BY DDH.DONDHID 
HAVING COUNT(distinct SP.LOAISPID) = 3
;
-- Tìm những khách hàng đặt trên 100 sản phẩm trong 1 hóa đơn
SELECT KH.KHID  FROM KHACHHANG KH
JOIN dondathang DDH ON DDH.khid = KH.KHID
JOIN chitietdondathang CTDDH ON CTDDH.dondhid = DDH.dondhid
WHERE CTDDH.SOLUONG >= 100
GROUP BY KH.KHID
;
SELECT * FROM KHACHHANG KH
JOIN dondathang DDH ON DDH.khid = KH.KHID
JOIN chitietdondathang CTDDH ON CTDDH.dondhid = DDH.dondhid
WHERE CTDDH.SOLUONG >= 100 ;
-- Hóa đơn có số lượng sản phẩm cao nhất là hóa đơn nào, bao nhiêu sản phẩm, gồm mấy loại sản phẩm.
SELECT ddh.dondhid , SUM(CTDDH.soluong * SP.GIABAN) GIATONGDON , SUM(CTDDH.SOLUONG) SL , COUNT(distinct LSP.LOAISPID) SUMSP FROM dondathang DDH 
JOIN chitietdondathang CTDDH ON CTDDH.dondhid = DDH.dondhid 
JOIN SANPHAM SP ON CTDDH.spid = SP.SPID
JOIN LOAISANPHAM LSP ON LSP.LOAISPID = SP.LOAISPID
GROUP BY ddh.dondhid 
order by GIATONGDON DESC LIMIT 1
;
-- Tìm những sản phẩm chỉ được đặt 1 lần duy nhất.
SELECT SP.SPID , SP.TENSP FROM SANPHAM SP
JOIN chitietdondathang CTDDH ON CTDDH.spid = SP.SPID
GROUP BY SP.SPID
HAVING COUNT(CTDDH.dondhid) = 1 
